/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CadastroProdutoController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author allan
 */
public class CadastroProdutoView extends javax.swing.JFrame {

    private final CadastroProdutoController controller;


    /**
     * Creates new form CadastroUsuarioView
     */
    public CadastroProdutoView() {
        initComponents();
        controller = new CadastroProdutoController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butVoltar = new javax.swing.JButton();
        campoEstoque = new javax.swing.JTextField();
        campoValorCusto = new javax.swing.JTextField();
        campoTaxaLucro = new javax.swing.JTextField();
        campoQtd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoDescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        butSalvar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        butVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        butVoltar.setText("Voltar");
        butVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(butVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 205, -1));
        getContentPane().add(campoEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 100, -1));
        getContentPane().add(campoValorCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 100, -1));
        getContentPane().add(campoTaxaLucro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 100, -1));
        getContentPane().add(campoQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 100, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estoque");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 100, -1));

        jLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("Quantidade");
        getContentPane().add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 100, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Taxa de Lucro");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 100, -1));

        jLabel1.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Produto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descrição");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 70, -1));
        getContentPane().add(campoDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 310, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor Custo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        butSalvar.setBackground(new java.awt.Color(0, 0, 0));
        butSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        butSalvar.setForeground(new java.awt.Color(255, 255, 255));
        butSalvar.setText("Salvar");
        butSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(butSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 205, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/fundo-cadastro-produto.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butSalvarActionPerformed
        
        try {
            controller.cadastrarProduto();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProdutoView.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_butSalvarActionPerformed

    private void butVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVoltarActionPerformed
        
        controller.voltarParaMenuPrincipal();
    }//GEN-LAST:event_butVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutoView().setVisible(true);
            }
        });
    }

    public JTextField getCampoDescricao() {
        return campoDescricao;
    }

    public void setCampoDescricao(JTextField campoDescricao) {
        this.campoDescricao = campoDescricao;
    }

    public JTextField getCampoEstoque() {
        return campoEstoque;
    }

    public void setCampoEstoque(JTextField campoEstoque) {
        this.campoEstoque = campoEstoque;
    }

    public JTextField getCampoQtd() {
        return campoQtd;
    }

    public void setCampoQtd(JTextField campoQtd) {
        this.campoQtd = campoQtd;
    }

    public JTextField getCampoTaxaLucro() {
        return campoTaxaLucro;
    }

    public void setCampoTaxaLucro(JTextField campoTaxaLucro) {
        this.campoTaxaLucro = campoTaxaLucro;
    }

    public JTextField getCampoValorCusto() {
        return campoValorCusto;
    }

    public void setCampoValorCusto(JTextField campoValorCusto) {
        this.campoValorCusto = campoValorCusto;
    }

    
    

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butSalvar;
    private javax.swing.JButton butVoltar;
    private javax.swing.JTextField campoDescricao;
    private javax.swing.JTextField campoEstoque;
    private javax.swing.JTextField campoQtd;
    private javax.swing.JTextField campoTaxaLucro;
    private javax.swing.JTextField campoValorCusto;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
