/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.VendaController;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author allan
 */
public class VendaView extends javax.swing.JFrame {
    
    private final VendaController controller;
    
    /**
     * Creates new form Agenda
     */
    public VendaView() {
        initComponents();
        controller = new VendaController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxFormaPagamento = new javax.swing.JComboBox<>();
        comboBoxCliente = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAgendamentos = new javax.swing.JTable();
        campoHora = new javax.swing.JFormattedTextField();
        comboBoxServico = new javax.swing.JComboBox<>();
        campoData = new javax.swing.JFormattedTextField();
        campoSubvalorProduto = new javax.swing.JTextField();
        comboBoxUsuario = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboBoxProduto = new javax.swing.JComboBox<>();
        campoValorTotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        butVoltar = new javax.swing.JButton();
        butGerarVenda = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoSubvalorServico = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboBoxFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Pix", "Débito", "Crédito" }));
        getContentPane().add(comboBoxFormaPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 120, 30));

        getContentPane().add(comboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 120, 30));

        tableAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cliente", "Serviço", "Barbeiro", "Valor", "Data", "Hora"
            }
        ));
        jScrollPane1.setViewportView(tableAgendamentos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 590, 160));

        try {
            campoHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(campoHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 120, 30));

        comboBoxServico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxServicoItemStateChanged(evt);
            }
        });
        getContentPane().add(comboBoxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 120, 30));

        try {
            campoData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(campoData, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 120, 30));
        getContentPane().add(campoSubvalorProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 120, 30));

        getContentPane().add(comboBoxUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 120, 30));

        jLabel6.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Selecionar Agendamento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Forma de Pgto");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Produto");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        comboBoxProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxProdutoItemStateChanged(evt);
            }
        });
        getContentPane().add(comboBoxProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 120, 30));
        getContentPane().add(campoValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 120, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Subvalor R$");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Valor Total R$");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        butVoltar.setText("Voltar");
        butVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(butVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 260, -1));

        butGerarVenda.setBackground(new java.awt.Color(0, 153, 153));
        butGerarVenda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        butGerarVenda.setForeground(new java.awt.Color(255, 255, 255));
        butGerarVenda.setText("Gerar Venda");
        butGerarVenda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        butGerarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butGerarVendaActionPerformed(evt);
            }
        });
        getContentPane().add(butGerarVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 260, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hora");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, -1, -1));
        getContentPane().add(campoSubvalorServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 120, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Subvalor R$");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Barbeiro");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Serviço");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cliente");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/fundo-venda.jpg"))); // NOI18N
        jLabel1.setText("jLabel2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 999, 607));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 160, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void butGerarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butGerarVendaActionPerformed
        
        controller.vender();
    }//GEN-LAST:event_butGerarVendaActionPerformed

    private void butVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butVoltarActionPerformed
        
        controller.voltarParaMenuPrincipal();
    }//GEN-LAST:event_butVoltarActionPerformed

    private void comboBoxServicoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxServicoItemStateChanged
        
        controller.atualizarValorServico();
    }//GEN-LAST:event_comboBoxServicoItemStateChanged

    private void comboBoxProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxProdutoItemStateChanged
        
        controller.atualizarValorProduto();
    }//GEN-LAST:event_comboBoxProdutoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaView().setVisible(true);
            }
        });
    }

    
    public JFormattedTextField getCampoData() {
        return campoData;
    }

    public void setCampoData(JFormattedTextField campoData) {
        this.campoData = campoData;
    }

    public JFormattedTextField getCampoHora() {
        return campoHora;
    }

    public void setCampoHora(JFormattedTextField campoHora) {
        this.campoHora = campoHora;
    }

    public JTextField getCampoSubvalorProduto() {
        return campoSubvalorProduto;
    }

    public void setCampoSubvalorProduto(JTextField campoSubvalorProduto) {
        this.campoSubvalorProduto = campoSubvalorProduto;
    }

    public JTextField getCampoSubvalorServico() {
        return campoSubvalorServico;
    }

    public void setCampoSubvalorServico(JTextField campoSubvalorServico) {
        this.campoSubvalorServico = campoSubvalorServico;
    }

    public JTextField getCampoValorTotal() {
        return campoValorTotal;
    }

    public void setCampoValorTotal(JTextField campoValorTotal) {
        this.campoValorTotal = campoValorTotal;
    }

    public JComboBox<String> getComboBoxCliente() {
        return comboBoxCliente;
    }

    public void setComboBoxCliente(JComboBox<String> comboBoxCliente) {
        this.comboBoxCliente = comboBoxCliente;
    }

    public JComboBox<String> getComboBoxFormaPagamento() {
        return comboBoxFormaPagamento;
    }

    public void setComboBoxFormaPagamento(JComboBox<String> comboBoxFormaPagamento) {
        this.comboBoxFormaPagamento = comboBoxFormaPagamento;
    }

    public JComboBox<String> getComboBoxProduto() {
        return comboBoxProduto;
    }

    public void setComboBoxProduto(JComboBox<String> comboBoxProduto) {
        this.comboBoxProduto = comboBoxProduto;
    }

    public JComboBox<String> getComboBoxServico() {
        return comboBoxServico;
    }

    public void setComboBoxServico(JComboBox<String> comboBoxServico) {
        this.comboBoxServico = comboBoxServico;
    }

    public JComboBox<String> getComboBoxUsuario() {
        return comboBoxUsuario;
    }

    public void setComboBoxUsuario(JComboBox<String> comboBoxUsuario) {
        this.comboBoxUsuario = comboBoxUsuario;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butGerarVenda;
    private javax.swing.JButton butVoltar;
    private javax.swing.JFormattedTextField campoData;
    private javax.swing.JFormattedTextField campoHora;
    private javax.swing.JTextField campoSubvalorProduto;
    private javax.swing.JTextField campoSubvalorServico;
    private javax.swing.JTextField campoValorTotal;
    private javax.swing.JComboBox<String> comboBoxCliente;
    private javax.swing.JComboBox<String> comboBoxFormaPagamento;
    private javax.swing.JComboBox<String> comboBoxProduto;
    private javax.swing.JComboBox<String> comboBoxServico;
    private javax.swing.JComboBox<String> comboBoxUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tableAgendamentos;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        controller.atualizarTabelaAgendamentos();
        controller.atualizarCliente();
        controller.atualizarServico();
        controller.atualizarValorServico();
        controller.atualizarProduto();
        controller.atualizarUsuario();
        controller.atualizarProduto();
    }

    public JTable getTableAgendamentos() {
        return tableAgendamentos;
    }

    public void setTableAgendamentos(JTable tableAgendamentos) {
        this.tableAgendamentos = tableAgendamentos;
    }
    
}


